In [14]:
import numpy as np
import pandas as pd
import chardet

In [15]:
with open('spam.csv', 'rb') as file:
  encoding = chardet.detect(file.read())['encoding']
  df1 = pd.read_csv('spam.csv', encoding=encoding,usecols=[0, 1,])
  print(df1)

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [11]:
df1

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [20]:
df1['class'] = df1.v1.map({'ham':0, 'spam':1})
df1

v1                                                 v2  class
0      0  Go until jurong point, crazy.. Available only ...    NaN
1      0                      Ok lar... Joking wif u oni...    NaN
2      1  Free entry in 2 a wkly comp to win FA Cup fina...    NaN
3      0  U dun say so early hor... U c already then say...    NaN
4      0  Nah I don't think he goes to usf, he lives aro...    NaN
...   ..                                                ...    ...
5567   1  This is the 2nd time we have tried 2 contact u...    NaN
5568   0              Will Ì_ b going to esplanade fr home?    NaN
5569   0  Pity, * was in mood for that. So...any other s...    NaN
5570   0  The guy did some bitching but I acted like i'd...    NaN
5571   0                         Rofl. Its true to its name    NaN

[5572 rows x 3 columns]

In [23]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
y = Y.astype('int')


In [24]:
print("X")
print(X)
print("y")
print(y)

X
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
y
[0 0 1 ... 0 0 0]


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()

In [26]:
vec.fit(X)
vec.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it

In [28]:
vec = CountVectorizer(stop_words=['end','on','is'] )
vec.fit(X)
vec.vocabulary_

{'go': 3549,
 'until': 8027,
 'jurong': 4348,
 'point': 5917,
 'crazy': 2327,
 'available': 1303,
 'only': 5534,
 'in': 4086,
 'bugis': 1751,
 'great': 3633,
 'world': 8486,
 'la': 4474,
 'buffet': 1749,
 'cine': 2048,
 'there': 7642,
 'got': 3593,
 'amore': 1069,
 'wat': 8264,
 'ok': 5502,
 'lar': 4510,
 'joking': 4316,
 'wif': 8389,
 'oni': 5530,
 'free': 3357,
 'entry': 2948,
 'wkly': 8444,
 'comp': 2165,
 'to': 7753,
 'win': 8402,
 'fa': 3086,
 'cup': 2386,
 'final': 3206,
 'tkts': 7740,
 '21st': 411,
 'may': 4928,
 '2005': 402,
 'text': 7592,
 '87121': 784,
 'receive': 6294,
 'question': 6187,
 'std': 7227,
 'txt': 7930,
 'rate': 6239,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6630,
 'so': 7021,
 'early': 2823,
 'hor': 3926,
 'already': 1042,
 'then': 7637,
 'nah': 5236,
 'don': 2712,
 'think': 7657,
 'he': 3780,
 'goes': 3557,
 'usf': 8072,
 'lives': 4663,
 'around': 1207,
 'here': 3830,
 'though': 7677,
 'freemsg': 3364,
 'hey': 3840,
 'darling': 2443,
 'it

In [29]:
print(vec.get_feature_names_out(input_features=None))
print(len(vec.get_feature_names_out(input_features=None)))

['00' '000' '000pes' ... 'ûò' 'ûówell' 'žö']
8670


In [30]:
X_transformed=vec.transform(X)
X_transformed

<5572x8670 sparse matrix of type '<class 'numpy.int64'>'
	with 72646 stored elements in Compressed Sparse Row format>

In [31]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
pd.DataFrame(X, columns=vec.get_feature_names())

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  ûò  \
0              0   0  ...   0         0    0    0     0   0        0   0   
1              0   0  ...   0         0    0    0     0   0        0   0   
2              0   0  ...   0         0    0    0     0   0        0   0   
3              0   0  ...   0         0    0    0     0   0        0   0   
4              0   0  ...   0         0    0    0     0   0        0   0   
...          ...  ..  ...  ..       ...  ...  ...   ...  ..      ...  ..   
5567           0   0  ...   0         0    0    0     0   0        0   0   
5568           0   0  ...   0         0    0    0     0   0        0   0   
5569           0   0  ...   0         0    0    0     0   0        0   0   
5570           0   0  ...   0         0    0    0     0   0        0   0   
5571           0   0  ...   0         0    0    0     0   0        0   0   

      ûówell  žö  
0          0   0  
1          0   0  
2          0   0  
3          0   0  
4          0   0  
...      ...  ..  
5567       0   0  
5568       0   0  
5569       0   0  
5570       0   0  
5571       0   0  

[5572 rows x 8670 columns]

In [33]:
df2 = pd.read_csv('test_text.csv') 
df2

Document  Class
0  very good educational institution      1

In [34]:
test_numpy_array = df2.to_numpy()
X_test = test_numpy_array[:,0]
y_test = test_numpy_array[:,1]
y_test = y_test.astype('int')
print("X_test")
print()
print("Y_test")
print(y_test)

X_test

Y_test
[1]


In [35]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<1x8670 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [36]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
from sklearn.naive_bayes import MultinomialNB

mnb=MultinomialNB()

mnb.fit(X,y)

mnb.predict_proba(X_test)

array([[0.99781143, 0.00218857]])

In [38]:
from sklearn.metrics import accuracy_score

y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)


Accuracy: 0.0
