In [31]:
import numpy as np
import pandas as pd

In [32]:
df1 = pd.read_csv('text.csv') 

In [33]:
df1

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [34]:
df1['Class'] = df1.Class.map({'cinemaa':0, 'education':1})
df1

Document  Class
0         Teclov is a great educational institution.    1.0
1            Educational greatness depends on ethics    1.0
2  A story of great ethics and educational greatness    1.0
3                           Sholey is a great cinema    NaN
4                   good movie depends on good story    NaN

In [35]:
X= df1['Document'].to_numpy()
Y = df1['Class'].to_numpy()
y = Y.astype('int')


In [36]:
print("X")
print(X)
print("y")
print(y)

X
['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
y
[          1           1           1 -2147483648 -2147483648]


In [37]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()

In [38]:
vec.fit(X)
vec.vocabulary_

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [39]:
vec = CountVectorizer(stop_words=['end','on','is'] )
vec.fit(X)
vec.vocabulary_

{'teclov': 13,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'ethics': 4,
 'story': 12,
 'of': 10,
 'and': 0,
 'sholey': 11,
 'cinema': 1,
 'good': 5,
 'movie': 9}

In [40]:
print(vec.get_feature_names_out(input_features=None))
print(len(vec.get_feature_names_out(input_features=None)))

['and' 'cinema' 'depends' 'educational' 'ethics' 'good' 'great'
 'greatness' 'institution' 'movie' 'of' 'sholey' 'story' 'teclov']
14


In [41]:
X_transformed=vec.transform(X)
X_transformed

<5x14 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [42]:
X=X_transformed.toarray()
X

array([[0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0]], dtype=int64)

In [43]:
pd.DataFrame(X, columns=vec.get_feature_names())

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


and  cinema  depends  educational  ethics  good  great  greatness  \
0    0       0        0            1       0     0      1          0   
1    0       0        1            1       1     0      0          1   
2    1       0        0            1       1     0      1          1   
3    0       1        0            0       0     0      1          0   
4    0       0        1            0       0     2      0          0   

   institution  movie  of  sholey  story  teclov  
0            1      0   0       0      0       1  
1            0      0   0       0      0       0  
2            0      0   1       0      1       0  
3            0      0   0       1      0       0  
4            0      1   0       0      1       0

In [44]:
df2 = pd.read_csv('test_text.csv') 
df2

Document  Class
0  very good educational institution      1

In [49]:
test_numpy_array = df2.to_numpy()
X_test = test_numpy_array[:,0]
y_test = test_numpy_array[:,1]
y_test = y_test.astype('int')
print("X_test")
print()
print("Y_test")
print(y_test)

X_test

Y_test
[1]


In [50]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<1x14 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [51]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [53]:
from sklearn.naive_bayes import MultinomialNB

mnb=MultinomialNB()

mnb.fit(X,y)

mnb.predict_proba(X_test)

array([[0.36411818, 0.63588182]])

In [56]:
from sklearn.metrics import accuracy_score

y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)


Accuracy: 1.0
